### ISSUE TITLE
Host Recommendation 

### ISSUE THREAD

**Issue by khalilbnd** [aminedh27/Github-Finder-App#1]
hey guess to u worked on a project that use github api for grabbing users information and thats cool only a recommendation, use some hosting services like netlify or vercel to visualize your website it will much easier for ppl to see your work including their code review (try gh-pages configuration to deploy your app) and good luck ^^

**Comment by aminedh27** [comment]
the App isn't finished yet I'm working on the design and the pages remaining I'll send you the link once I deployed

**Comment by aminedh27** [comment]
Here is the Link to the app you can try it

https://github-finder-amdh.netlify.app/user/khalilbnd
